FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

LABEL version="6.0" \
	  description="Image to create IoT Traffic Lights Api" \
	  maintainer="marcin.narloch@qbituniverse.com"

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TrafficLights/TrafficLights.Api/TrafficLights.Api.csproj", "TrafficLights.Api/"]
RUN dotnet restore "TrafficLights.Api/TrafficLights.Api.csproj"

COPY TrafficLights .
WORKDIR "/src/TrafficLights.Api"
RUN dotnet build "TrafficLights.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TrafficLights.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "TrafficLights.Api.dll"]