FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

LABEL version="6.0" \
	  description="Image to create IoT Traffic Lights Web" \
	  maintainer="marcin.narloch@qbituniverse.com"

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TrafficLights/TrafficLights.Web/TrafficLights.Web.csproj", "TrafficLights.Web/"]
RUN dotnet restore "TrafficLights.Web/TrafficLights.Web.csproj"

COPY TrafficLights .
WORKDIR "/src/TrafficLights.Web"
RUN dotnet build "TrafficLights.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TrafficLights.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "TrafficLights.Web.dll"]