FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

LABEL version="6.0" \
	  description="Image to create IoT HeS Admin API" \
	  maintainer="marcin.narloch@qbituniverse.com"

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["HeS/HeS.Admin.Api/HeS.Admin.Api.csproj", "HeS.Admin.Api/"]
RUN dotnet restore "HeS.Admin.Api/HeS.Admin.Api.csproj"

COPY HeS .
WORKDIR "/src/HeS.Admin.Api"
RUN dotnet build "HeS.Admin.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HeS.Admin.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "HeS.Admin.Api.dll"]